apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kapp.k14s.io/change-group: hackaton.code.vmware.com/rbac
  name: demo-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kapp.k14s.io/change-group: hackaton.code.vmware.com/rbac
  name: demo-sa-admin
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: demo-sa
  namespace: default
